FROM ubuntu:latest AS build

# Build dependencies
RUN apt update && apt install -y \
	rapidjson-dev \
	zlib1g-dev \
	libncurses-dev \
	gcc g++ make git

RUN git clone -b custom-address https://git.sr.ht/~valcarcexyz/tetra-kit /app/tetra-kit
WORKDIR /app/tetra-kit
RUN ./build.sh
RUN cp decoder/decoder /app
RUN cp recorder/recorder /app
WORKDIR /app
