services:
  phy:
    build:
      context: .
      dockerfile: Dockerfile.phy
    devices:
      - /dev/bus/usb/003/006
    shm_size: '2g'
  decoder:
    build:
      context: .
      dockerfile: Dockerfile.tetra-kit
    entrypoint: /app/decoder
    ports:
      - 42001:42001
  
  recorder:
    build:
      context: .
      dockerfile: Dockerfile.tetra-kit
    entrypoint: /app/recorder
