services:
  phy:
    build:
      context: .
      dockerfile: Dockerfile.phy
    device_cgroup_rules:
      - "c 189:* rwm"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    shm_size: '2g'
    environment:
      - FREQ=424.0005
      - GAIN=49.6
      - RTLSERIAL=00000005
  decoder:
    build:
      context: .
      dockerfile: Dockerfile.tetra-kit
    entrypoint: /app/decoder
  
  recorder:
    build:
      context: .
      dockerfile: Dockerfile.tetra-kit
    entrypoint: /app/recorder
    volumes:
      - ./log.txt:/app/log.txt
      - ./raw:/app/raw

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - ./log.txt:/app/log.txt
      - ./raw:/app/raw
    environment:
      - PORT=8443
      - USERNAME=admin
      - PASSWORD=password
      - SECURE=false
      - PUBLIC=false
      - TETRA_KIT_PATH=/app/raw
      - TETRA_KIT_LOG_PATH=/app/log.txt
    ports:
      - 8443:8443
